
# Tubmlr Keywords 

KW_ITERATOR = {
    "block:Posts": "post",
    "block:Photos": "photo",
    "block:Lines": "line",
    "block:VideoThumbnails": "videoThumbnail",
    "block:GroupMembers": "groupMember",
    "block:FeaturedTags": "featureTag",
    "block:Pages": "page",
    "block:PostNotes": "postNote",
    "block:Tags": "tag",
    "block:GroupMembers": "groupMember",
    "block:Followed": "followed",
    #"block:Likes": "like",
    "block:RelatedPosts": "relatedPost",
}

"""
NOTE:
`block:variable_name} style keyword will be converted to
`{% if variable_name %}, so ignored

"""

KW_VARS = [
    # Basic vars
    "Title",
    "Description",
    "MetaDescription",
    "BlogURL",
    "RSS",
    "Favicon",
    "CustomCSS",
    "block:PermalinkPage",
    "block:IndexPage",
    "block:HomePage",
    #"block:PostTitle",
    "PostTitle",
    #"block:PostSummary",
    "PostSummary",
    "PortraitURL-16",
    "PortraitURL-24",
    "PortraitURL-30",
    "PortraitURL-40",
    "PortraitURL-48",
    "PortraitURL-64",
    "PortraitURL-96",
    "PortraitURL-128",
    "CopyrightYears",

#appearance
    "TitleFont",
    "TitleFontWeight",
    "BackgroundColor",
    "TitleColor",
    "AccentColor",
    "HeaderImage",
    "AvatarShape",
    "block:ShowTitle",
    "block:HideTitle",
    "block:ShowDescription",
    "block:HideDescription",
    "block:ShowAvatar",
    "block:HideAvatar",
    "block:ShowHeaderImage",
    "block:HideHeaderImage",

#navigation
    "block:Pagination",
    #"block:PreviousPage",
    #"block:NextPage",
    "PreviousPage",
    "NextPage",
    "CurrentPage",
    "TotalPages",
    "block:SubmissionsEnabled",
    "SubmitLabel",
    "block:AskEnabled",
    "AskLabel",

# page jump
    "block:JumpPagination",
    "block:CurrentPage",
    "block:JumpPage",
    "PageNumber",
    "URL",

#page management
    "block:HasPages",
    "block:Pages",
    "URL",
    "Label",

# permalink navigation
    "block:PermalinkPagination",
    #"block:PreviousPost",
    #"block:NextPost",
    "PreviousPost",
    "NextPost",

# post
    "block:Posts",
    "block:Text",
    "block:Answer",
    "block:Photo",
    "block:Panorama",
    "block:Photoset",
    "block:Quote",
    "block:Link",
    "block:Chat",
    "block:Audio",
    "block:Video",
    "PostType",
    "Permalink",
    "RelativePermalink",
    "ShortURL",
    "EmbedUrl",
    "PostID",
    "TagsAsClasses",
    "block:Post1",
    "block:Post2",
    "block:Post3",
    "block:Post4",
    "block:Post5",
    "block:Post6",
    "block:Post7",
    "block:Post8",
    "block:Post9",
    "block:Post10",
    "block:Post11",
    "block:Post12",
    "block:Post13",
    "block:Post14",
    "block:Post15",
    "block:Odd",
    "block:Even",
    "block:More",
    "PostNotesURL",
    "NPF",
    #"block:PinnedPostLabel",
    "PinnedPostLabel",
    
    # reblog
    "block:NotReblog",
    "block:RebloggedFrom",
    "ReblogParentName",
    "ReblogParentTitle",
    "ReblogParentURL",
    "ReblogParentPortraitURL-16",
    "ReblogParentPortraitURL-24",
    "ReblogParentPortraitURL-30",
    "ReblogParentPortraitURL-40",
    "ReblogParentPortraitURL-48",
    "ReblogParentPortraitURL-64",
    "ReblogParentPortraitURL-96",
    "ReblogParentPortraitURL-128",
    "ReblogRootName",
    "ReblogRootTitle",
    "ReblogRootURL",
    "ReblogRootPortraitURL-16",
    "ReblogRootPortraitURL-24",
    "ReblogRootPortraitURL-30",
    "ReblogRootPortraitURL-40",
    "ReblogRootPortraitURL-48",
    "ReblogRootPortraitURL-64",
    "ReblogRootPortraitURL-96",
    "ReblogRootPortraitURL-128",
    "block:Reblogs",
    "block:IsActive",
    "block:IsDeactivated",
    "Username",
    "block:HasPermalink",
    "Permalink",
    "block:HasAvatar",
    "PortraitURL-16",
    "PortraitURL-24",
    "PortraitURL-30",
    "PortraitURL-40",
    "PortraitURL-48",
    "PortraitURL-64",
    "PortraitURL-96",
    "PortraitURL-128",
    "block:isOriginalEntry",
    "Body",
    
    # legacy text post
    #"block:Title",
    "Title",
    "Body",
    
    # legacy image post
    "PhotoAlt",
    #"block:Caption",
    "Caption",
    #"block:LinkURL",
    "LinkURL",
    "LinkOpenTag",
    "LinkCloseTag",
    "PhotoURL-500",
    "PhotoWidth-500",
    "PhotoHeight-500",
    "PhotoURL-400",
    "PhotoWidth-400",
    "PhotoHeight-400",
    "PhotoURL-250",
    "PhotoWidth-250",
    "PhotoHeight-250",
    "PhotoURL-100",
    "PhotoWidth-100",
    "PhotoHeight-100",
    "PhotoURL-75sq",
    "block:HighRes",
    "PhotoURL-HighRes",
    "PhotoWidth-HighRes",
    "PhotoHeight-HighRes",
    "block:Exif",
    #"block:Camera",
    "Camera",
    #"block:Aperture",
    "Aperture",
    #"block:Exposure",
    "Exposure",
    #"block:FocalLength",
    "FocalLength",
    
    # legacy panorama post
    "LinkOpenTag",
    "LinkCloseTag",
    "PhotoURL-Panorama",
    "PhotoWidth-Panorama",
    "PhotoHeight-Panorama",
    
    # legacy photo set
    #"block:Caption",
    "Caption",
    "Photoset",
    "Photoset-700",
    "Photoset-500",
    "Photoset-400",
    "Photoset-250",
    "PhotoCount",
    "PhotosetLayout",
    "JSPhotosetLayout",
    #"block:Photos", # iterator
    
    #legacy quote post
    "Quote",
    #"block:Source",
    "Source",
    "Length",
    
    # legacy link post
    "URL",
    "Name",
    "Target",
    #"block:Host",
    "Host",
    #"block:Thumbnail",
    "Thumbnail",
    "Thumbnail-HighRes",
    #"block:Description",
    "Description",
    #"block:Author",
    "Author",
    #"block:Excerpt",
    "Excerpt",
    
    # legacy chat post
    #"block:Title",
    "Title",
    #"block:Lines", #itereator
    #"block:Label",
    "Label",
    "Name",
    "Line",
    "UserNumber",
    "Alt",
    
    # legacy audio post
    #"block:Caption",
    "Caption",
    #"block:AudioEmbed",
    "AudioEmbed",
    "AudioEmbed-250",
    "AudioEmbed-400",
    "AudioEmbed-500",
    "AudioEmbed-640",
    #"block:AudioPlayer",
    "AudioPlayer",
    "RawAudioURL",
    #"block:PlayCount",
    "PlayCount",
    "FormattedPlayCount",
    "PlayCountWithLabel",
    #"block:ExternalAudio",
    "ExternalAudioURL",
    #"block:AlbumArt",
    "AlbumArtURL",
    #"block:Artist",
    "Artist",
    #"block:Album",
    "Album",
    #"block:TrackName",
    "TrackName",
    
    # legacy video post
    #"block:Caption",
    "Caption",
    "Video-700",
    "Video-500",
    "Video-400",
    "Video-250",
    "VideoEmbed-700",
    "VideoEmbed-500",
    "VideoEmbed-400",
    "VideoEmbed-250",
    "PlayCount",
    "FormattedPlayCount",
    "PlayCountWithLabel",
    "block:VideoThumbnail",
    "VideoThumbnailURL",
    #"block:VideoThumbnails", # iterator
    "VideoThumbnailURL",
    
    #legacy question post
    "Question",
    "Answer",
    "Asker",
    "AskerPortraitURL-16",
    "AskerPortraitURL-24",
    "AskerPortraitURL-30",
    "AskerPortraitURL-40",
    "AskerPortraitURL-48",
    "AskerPortraitURL-64",
    "AskerPortraitURL-96",
    "AskerPortraitURL-128",
    #"block:Answerer",
    "Answerer",
    "AnswererPortraitURL-16",
    "AnswererPortraitURL-24",
    "AnswererPortraitURL-30",
    "AnswererPortraitURL-40",
    "AnswererPortraitURL-48",
    "AnswererPortraitURL-64",
    "AnswererPortraitURL-96",
    "AnswererPortraitURL-128",
    "Replies",
    
    # date
    "block:Date",
    "block:NewDayDate",
    "block:SameDayDate",
    "DayOfMonth",
    "DayOfMonthWithZero",
    "DayOfWeek",
    "ShortDayOfWeek",
    "DayOfWeekNumber",
    "DayOfMonthSuffix",
    "DayOfYear",
    "WeekOfYear",
    "Month",
    "ShortMonth",
    "MonthNumber",
    "MonthNumberWithZero",
    "Year",
    "ShortYear",
    "AmPm",
    "CapitalAmPm",
    "12Hour",
    "24Hour",
    "12HourWithZero",
    "24HourWithZero",
    "Minutes",
    "Seconds",
    "Beats",
    "Timestamp",
    "TimeAgo",
    
    # reaction
    #"block:PostNotes",
    "PostNotes",
    "PostNotes-16",
    "PostNotes-64",
    #"block:NoteCount",
    "NoteCount",
    "NoteCountWithLabel",
    #"block:LikeCount",
    "LikeCount",
    #"block:ReblogCount",
    "ReblogCount",
    #"block:ReplyCount",
    "ReplyCount",
    
    # tag
    "block:HasTags",
    "Tag",
    "URLSafeTag",
    "TagURL",
    "TagURLChrono",
    
    # content source
    "block:ContentSource",
    "SourceURL",
    "block:SourceLogo",
    "BlackLogoURL",
    "LogoWidth",
    "LogoHeight",
    "SourceTitle",
    #"block:NoSourceLogo", # negative operator
    
    # guest post
    "block:Submission",
    "Submitter",
    "SubmitterURL",
    "SubmitterPortraitURL-16",
    "SubmitterPortraitURL-24",
    "SubmitterPortraitURL-30",
    "SubmitterPortraitURL-40",
    "SubmitterPortraitURL-48",
    "SubmitterPortraitURL-64",
    "SubmitterPortraitURL-96",
    "SubmitterPortraitURL-128",
    
    # group blog member
    #"block:GroupMembers", # iterator
    "block:GroupMember",
    "GroupMemberName",
    "GroupMemberTitle",
    "GroupMemberURL",
    "GroupMemberPortraitURL-16",
    "GroupMemberPortraitURL-24",
    "GroupMemberPortraitURL-30",
    "GroupMemberPortraitURL-40",
    "GroupMemberPortraitURL-48",
    "GroupMemberPortraitURL-64",
    "GroupMemberPortraitURL-96",
    "GroupMemberPortraitURL-128",
    
    #group blog author
    "PostAuthorName",
    "PostAuthorTitle",
    "PostAuthorURL",
    "PostAuthorPortraitURL-16",
    "PostAuthorPortraitURL-24",
    "PostAuthorPortraitURL-30",
    "PostAuthorPortraitURL-40",
    "PostAuthorPortraitURL-48",
    "PostAuthorPortraitURL-64",
    "PostAuthorPortraitURL-96",
    "PostAuthorPortraitURL-128",
    
    # day page
    "block:DayPage",
    "block:DayPagination",
    #"block:PreviousDayPage",
    #"block:NextDayPage",
    "PreviousDayPage",
    "NextDayPage",
    
    # tag page
    "block:TagPage",
    "Tag",
    "URLSafeTag",
    "TagURL",
    "TagURLChrono",
    
    # search
    "SearchQuery",
    "URLSafeSearchQuery",
    "block:SearchPage",
    "SearchResultCount",
    "block:NoSearchResults",
    "block:HideFromSearchEnabled",
    
    #feature tag
    "block:HasFeaturedTags",
    #"block:FeaturedTags", # iterator
    "Tag",
    "URLSafeTag",
    "TagURL",
    "TagURLChrono",
    
    # following
    "block:Following",
    "block:Followed",
    "FollowedName",
    "FollowedTitle",
    "FollowedURL",
    "FollowedPortraitURL-16",
    "FollowedPortraitURL-24",
    "FollowedPortraitURL-30",
    "FollowedPortraitURL-40",
    "FollowedPortraitURL-48",
    "FollowedPortraitURL-64",
    "FollowedPortraitURL-96",
    "FollowedPortraitURL-128",
    
    # like
    "block:Likes",
    "block:NoLikes",
    "Likes",
    
    # like button
    "LikeButton",
    
    # reblog button
    "ReblogButton",
    "block:RelatedPosts",
    
    # undocumented
    "block:Hidden",
    "MobileAppHeaders",
    "block:LikesPage",
    "block:FollowingPage",
    "block:ShowAdsOnThisPage",
    "block:NewCta",
    "block:StretchHeaderImage",
    "HeaderImage-640",
    "block:ShareFollowing",
    "AdPositions",
]

KW_NEGATIVE_CONDITIONS = [
    # undocumented
    "block:NoFollowing",
    "block:NoStretchHeaderImage",
    "block:NoPosts",
]

KW_ANTONYM = [
    ("block:ShowTitle", "block:HideTitle"),
    ("block:ShowDescription", "block:HideDescription"),
    ("block:ShowAvatar", "block:HideAvatar"),
    ("block:ShowHeaderImage", "block:HideHeaderImage"),
]
